on:
  workflow_dispatch:
  schedule:
    # Every 12 hours
    - cron: 0 */12 * * *

jobs:
  update_formula:
    name: Update composer Formula
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@master

      - name: Download latest formula
        run: wget https://raw.githubusercontent.com/Homebrew/homebrew-core/HEAD/Formula/composer.rb -O /tmp/composer.rb

      - name: Replace dependency
        run: cat /tmp/composer.rb | sed 's|depends_on "php"|depends_on "shivammathur/php/php"|g' > ./Formula/composer.rb
      
      - name: Publish changes
        uses: EndBug/add-and-commit@v7
        with:
          committer_name: Homebrew Sync
          message: Update formula to latest version